apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sa-2020-03-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /otusapp($|/)(.*)
          backend:
            serviceName: sa-2020-03-app-service
            servicePort: 9000 
